//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ramss.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ramss.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseCode,courseNum,PreReq
        ///CPS,101,
        ///CPS,109,
        ///CPS,118,
        ///CPS,125,
        ///CPS,209,109
        ///CPS,213,
        ///CPS,305,393
        ///CPS,310,213
        ///CPS,311,
        ///CPS,313,
        ///CPS,314,
        ///CPS,315,
        ///CPS,393,
        ///CPS,406,
        ///CPS,40A/B,
        ///CPS,411,
        ///CPS,412,
        ///CPS,420,
        ///CPS,501,
        ///CPS,506,
        ///CPS,510,
        ///CPS,511,
        ///CPS,513,
        ///CPS,530,
        ///CPS,590,
        ///CPS,603,
        ///CPS,606,
        ///CPS,607,
        ///CPS,610,
        ///CPS,613,
        ///CPS,615,
        ///CPS,616,
        ///CPS,621,
        ///CPS,630,
        ///CPS,633,
        ///CPS,650,
        ///CPS,706,
        ///CPS,707,
        ///CPS,710,
        ///CPS,713,
        ///CPS,714,
        ///CPS,716,
        ///CPS,721,
        ///CPS,730,
        ///CPS,750,
        ///CPS,752,
        ///CPS,801,
        ///CP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string courseListing {
            get {
                return ResourceManager.GetString("courseListing", resourceCulture);
            }
        }
    }
}
